variable "project_name" {
  description = "Project name used in resource names and tags."
  type        = string
}

variable "environment" {
  description = "Environment name used in resource tags."
  type        = string
}

variable "db_username" {
  description = "Master username for Temporal PostgreSQL database."
  type        = string
  default     = "temporal"
}

variable "rds_endpoint" {
  description = "RDS endpoint hostname (from rds_temporal module output)."
  type        = string
}

variable "db_password" {
  description = "Master password for Temporal PostgreSQL database (generated by the root module)."
  type        = string
  sensitive   = true
}
